# Generated by Django 4.2.1 on 2023-06-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_users_alter_project_author'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='projects',
            field=models.ManyToManyField(blank=True, to='project.project'),
        ),
    ]
