# Generated by Django 4.2.1 on 2023-06-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('user', '0002_remove_projectuser_name_remove_projectuser_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='projects',
            field=models.ManyToManyField(to='project.project'),
        ),
    ]
