# Generated by Django 4.2.1 on 2023-06-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_projectuser_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='projects',
        ),
    ]
