# Generated by Django 4.2.1 on 2023-06-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField()),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('PENDING', 'In pending'), ('PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='NEW', max_length=12)),
            ],
        ),
    ]
